name: ci-docker-multi-arch
on:
  push:
    branches:
      - multiarch
  workflow_dispatch:

jobs:
  docker:
    name: Build base image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }} 

      - name: Get Release Tag
        run: |
             echo "VERSION=v1" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./deploy/docker
          push: false
          tags: rajburnwal07/pebblo:${{ env.VERSION }}
          platforms: linux/amd64,linux/arm64
          file: ./deploy/docker/Dockerfile.base
          build-args: |
                      "build_image=python:3.11"
                      "base_image=python:3.11"
                      "pebblo_version=${{ env.VERSION }}"